[1] 4.425362 5.813723 3.967865 3.450883 7.227823 3.858484 5.071205 4.986693
  [9] 4.108031 5.168664 3.007809 4.749752 6.203988 4.562359 4.650732 4.954731
 [17] 3.393261 4.390848 4.292548 5.100629 4.958374 5.233742 3.269042 7.015831
 [25] 4.560587 6.567135 5.341944 4.704490 6.352518 4.967895 5.325588 4.129111
 [33] 3.996234 4.682725 5.775114 4.988419 4.660054 5.515684 6.601094 5.932947
 [41] 3.841166 6.203898 4.385842 6.171689 3.180918 4.824788 5.494977 5.365206
 [49] 2.640083 5.393157 5.294516 4.967802 4.801838 6.070998 3.470871 5.563124
 [57] 5.618766 5.674599 5.495227 2.916874 4.376959 5.577867 3.806600 5.036539
 [65] 5.591808 4.711933 5.394155 4.442705 4.787623 4.678369 4.553172 4.664493
 [73] 4.851551 6.611185 6.195031 6.073592 5.455983 5.088676 5.523896 4.074260
 [81] 3.308569 5.276714 5.754107 7.438541 6.583801 3.970619 5.372668 5.382180
 [89] 7.267597 5.608740 6.600095 3.838449 5.313596 5.677026 6.912862 4.445289
 [97] 3.246022 2.990110 5.737322 4.156403

In [63]:
p <- 5
n <- 10
R <- 100
gamma <- 0.1
c <- 1.1
x = matrix(rnorm(n*p), n, p)
y = matrix(rnorm(n*p), n, 1)

sim <- vector("numeric", length = R)


In [26]:
sim

[1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [38] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [75] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [66]:
psi <- apply(x, 2, function(x) mean(x^2))
tXtpsi <- t(t(x)/sqrt(psi))

In [28]:
for (l in 1:R) {
    g <- matrix(rep( rnorm(n), each = p), ncol = p, byrow = TRUE)
    sim[l] <- n * max(2 * abs(colMeans(tXtpsi * g)))
}

lambda0 <- c * quantile(sim, probs = 1 - gamma)
lambda0

90% 
15.76201

In [68]:
xehat <- x*ehat
psi <- apply(xehat, 2, function(x) mean(x^2))
tXehattpsi <- t(t(xehat)/sqrt(psi))
tXehattpsi

[,1]         [,2]          [,3]          [,4]         [,5]        
 [1,]  0.001478218  0.0000465011  0.0003472686  0.001871991 -0.004444233
 [2,]  1.177600788  0.2134777494  0.8458656836  0.056400232 -0.920226988
 [3,] -0.093188779 -0.5847245823  1.7024743405 -1.749436117 -0.370235832
 [4,]  0.875589879 -0.0868674905  0.7530407647  0.068596914  0.634532173
 [5,]  0.203159523 -2.1395446637  1.9394967163 -0.965173427  1.180126028
 [6,]  1.895428894 -1.7821634640  1.1753084186  2.236662304  2.090283289
 [7,]  0.055684977 -0.2338843895  0.3094483158 -0.339620416 -0.420083030
 [8,] -0.088342595 -0.0463040327  0.0240176963 -0.008780368  0.399525949
 [9,] -0.613121801  1.2411949268 -0.5428512743  0.291072204 -0.658965825
[10,]  1.953756473  0.5037952485 -0.5338556402 -0.892873502 -1.442618634

In [81]:
xehat

[,1]         [,2]          [,3]          [,4]         [,5]        
 [1,]  0.001448542  0.0000559784  0.0003555366  0.001567455 -0.002148545
 [2,]  1.153960349  0.2569862021  0.8660045433  0.047225042 -0.444879714
 [3,] -0.091318006 -0.7038960741  1.7430078349 -1.464837862 -0.178988894
 [4,]  0.858012336 -0.1045717717  0.7709695950  0.057437569  0.306761805
 [5,]  0.199081078 -2.5756007780  1.9856733766 -0.808159021  0.570526769
 [6,]  1.857377994 -2.1453824649  1.2032908416  1.872802096  1.010538317
 [7,]  0.054567096 -0.2815518768  0.3168158404 -0.284370969 -0.203087304
 [8,] -0.086569110 -0.0557411606  0.0245895235 -0.007351978  0.193149073
 [9,] -0.600813327  1.4941602638 -0.5557757916  0.243720580 -0.318574147
[10,]  1.914534642  0.6064727024 -0.5465659842 -0.747620847 -0.697427672

In [82]:
sqrt(psi)

[1] 0.9799249 1.2038079 1.0238086 0.8373200 0.4834456

In [80]:
x*ehat

[,1]         [,2]          [,3]          [,4]         [,5]        
 [1,]  0.001448542  0.0000559784  0.0003555366  0.001567455 -0.002148545
 [2,]  1.153960349  0.2569862021  0.8660045433  0.047225042 -0.444879714
 [3,] -0.091318006 -0.7038960741  1.7430078349 -1.464837862 -0.178988894
 [4,]  0.858012336 -0.1045717717  0.7709695950  0.057437569  0.306761805
 [5,]  0.199081078 -2.5756007780  1.9856733766 -0.808159021  0.570526769
 [6,]  1.857377994 -2.1453824649  1.2032908416  1.872802096  1.010538317
 [7,]  0.054567096 -0.2815518768  0.3168158404 -0.284370969 -0.203087304
 [8,] -0.086569110 -0.0557411606  0.0245895235 -0.007351978  0.193149073
 [9,] -0.600813327  1.4941602638 -0.5557757916  0.243720580 -0.318574147
[10,]  1.914534642  0.6064727024 -0.5465659842 -0.747620847 -0.697427672

In [75]:
xehat

[,1]         [,2]          [,3]          [,4]         [,5]        
 [1,]  0.001448542  0.0000559784  0.0003555366  0.001567455 -0.002148545
 [2,]  1.153960349  0.2569862021  0.8660045433  0.047225042 -0.444879714
 [3,] -0.091318006 -0.7038960741  1.7430078349 -1.464837862 -0.178988894
 [4,]  0.858012336 -0.1045717717  0.7709695950  0.057437569  0.306761805
 [5,]  0.199081078 -2.5756007780  1.9856733766 -0.808159021  0.570526769
 [6,]  1.857377994 -2.1453824649  1.2032908416  1.872802096  1.010538317
 [7,]  0.054567096 -0.2815518768  0.3168158404 -0.284370969 -0.203087304
 [8,] -0.086569110 -0.0557411606  0.0245895235 -0.007351978  0.193149073
 [9,] -0.600813327  1.4941602638 -0.5557757916  0.243720580 -0.318574147
[10,]  1.914534642  0.6064727024 -0.5465659842 -0.747620847 -0.697427672

In [74]:
xehat

[1] 0.9602528 1.4491535 1.0481840 0.7011048 0.2337197

In [72]:
sqrt(psi)

[1] 0.9799249 1.2038079 1.0238086 0.8373200 0.4834456

In [71]:
xehat

[,1]         [,2]          [,3]          [,4]         [,5]        
 [1,]  0.001448542  0.0000559784  0.0003555366  0.001567455 -0.002148545
 [2,]  1.153960349  0.2569862021  0.8660045433  0.047225042 -0.444879714
 [3,] -0.091318006 -0.7038960741  1.7430078349 -1.464837862 -0.178988894
 [4,]  0.858012336 -0.1045717717  0.7709695950  0.057437569  0.306761805
 [5,]  0.199081078 -2.5756007780  1.9856733766 -0.808159021  0.570526769
 [6,]  1.857377994 -2.1453824649  1.2032908416  1.872802096  1.010538317
 [7,]  0.054567096 -0.2815518768  0.3168158404 -0.284370969 -0.203087304
 [8,] -0.086569110 -0.0557411606  0.0245895235 -0.007351978  0.193149073
 [9,] -0.600813327  1.4941602638 -0.5557757916  0.243720580 -0.318574147
[10,]  1.914534642  0.6064727024 -0.5465659842 -0.747620847 -0.697427672

In [70]:
psi

[1] 0.9602528 1.4491535 1.0481840 0.7011048 0.2337197

In [50]:
vector = c(6.52276955293844, 6.210569320588091, 4.7864301479581, 9.1187992502725, 8.42000515087866, 6.17048265730705)

In [51]:
quantile(vector, probs = 1 - gamma)

90% 
8.769402

In [55]:
g <- matrix(rep( rnorm(n), each = p), ncol = p, byrow = TRUE)

In [30]:
n * max(2 * abs(colMeans(tXtpsi * g)))

[1] 14.73839

In [58]:
rep(eh, each = p)

[1] -0.204668625 -0.204668625 -0.204668625 -0.204668625 -0.204668625
  [6]  1.693112103  1.693112103  1.693112103  1.693112103  1.693112103
 [11]  0.028110914  0.028110914  0.028110914  0.028110914  0.028110914
 [16]  1.244014377  1.244014377  1.244014377  1.244014377  1.244014377
 [21] -1.834450702 -1.834450702 -1.834450702 -1.834450702 -1.834450702
 [26]  1.188932078  1.188932078  1.188932078  1.188932078  1.188932078
 [31]  1.176205826  1.176205826  1.176205826  1.176205826  1.176205826
 [36] -1.216855454 -1.216855454 -1.216855454 -1.216855454 -1.216855454
 [41] -0.132117077 -0.132117077 -0.132117077 -0.132117077 -0.132117077
 [46] -1.432923536 -1.432923536 -1.432923536 -1.432923536 -1.432923536
 [51]  1.175114398  1.175114398  1.175114398  1.175114398  1.175114398
 [56]  0.439459728  0.439459728  0.439459728  0.439459728  0.439459728
 [61]  0.553490544  0.553490544  0.553490544  0.553490544  0.553490544
 [66] -0.450457342 -0.450457342 -0.450457342 -0.450457342 -0.450457342
 [71] -1.059373799 -1.059373799 -1.059373799 -1.059373799 -1.059373799
 [76]  0.746863158  0.746863158  0.746863158  0.746863158  0.746863158
 [81] -0.935052770 -0.935052770 -0.935052770 -0.935052770 -0.935052770
 [86] -1.064922062 -1.064922062 -1.064922062 -1.064922062 -1.064922062
 [91] -0.016488574 -0.016488574 -0.016488574 -0.016488574 -0.016488574
 [96] -0.038736814 -0.038736814 -0.038736814 -0.038736814 -0.038736814
[101] -0.306182250 -0.306182250 -0.306182250 -0.306182250 -0.306182250
[106]  0.154913348  0.154913348  0.154913348  0.154913348  0.154913348
[111] -2.039519865 -2.039519865 -2.039519865 -2.039519865 -2.039519865
[116] -0.527787437 -0.527787437 -0.527787437 -0.527787437 -0.527787437
[121] -0.235280443 -0.235280443 -0.235280443 -0.235280443 -0.235280443
[126] -0.251788502 -0.251788502 -0.251788502 -0.251788502 -0.251788502
[131] -1.403845237 -1.403845237 -1.403845237 -1.403845237 -1.403845237
[136]  0.336908754  0.336908754  0.336908754  0.336908754  0.336908754
[141]  1.135591519  1.135591519  1.135591519  1.135591519  1.135591519
[146] -0.802283461 -0.802283461 -0.802283461 -0.802283461 -0.802283461
[151] -0.044127194 -0.044127194 -0.044127194 -0.044127194 -0.044127194
[156]  0.079759397  0.079759397  0.079759397  0.079759397  0.079759397
[161]  0.628642423  0.628642423  0.628642423  0.628642423  0.628642423
[166]  0.847145711  0.847145711  0.847145711  0.847145711  0.847145711
[171]  0.796342156  0.796342156  0.796342156  0.796342156  0.796342156
[176]  1.291597528  1.291597528  1.291597528  1.291597528  1.291597528
[181]  0.669658421  0.669658421  0.669658421  0.669658421  0.669658421
[186]  0.005281859  0.005281859  0.005281859  0.005281859  0.005281859
[191] -0.823219794 -0.823219794 -0.823219794 -0.823219794 -0.823219794
[196]  1.286303084  1.286303084  1.286303084  1.286303084  1.286303084
[201]  0.778495287  0.778495287  0.778495287  0.778495287  0.778495287
[206]  0.188986452  0.188986452  0.188986452  0.188986452  0.188986452
[211] -1.096585161 -1.096585161 -1.096585161 -1.096585161 -1.096585161
[216]  2.173696801  2.173696801  2.173696801  2.173696801  2.173696801
[221]  0.379283906  0.379283906  0.379283906  0.379283906  0.379283906
[226] -1.543616497 -1.543616497 -1.543616497 -1.543616497 -1.543616497
[231] -1.271302537 -1.271302537 -1.271302537 -1.271302537 -1.271302537
[236]  0.665554916  0.665554916  0.665554916  0.665554916  0.665554916
[241]  0.217816255  0.217816255  0.217816255  0.217816255  0.217816255
[246] -2.157455029 -2.157455029 -2.157455029 -2.157455029 -2.157455029

In [64]:
y

[,1]        
 [1,] -0.000984857
 [2,]  0.471993718
 [3,] -1.005882635
 [4,] -0.524737426
 [5,] -1.444355676
 [6,]  1.610965207
 [7,] -0.362085576
 [8,]  0.186716429
 [9,]  0.678388275
[10,]  1.654282282

In [65]:
eh <- y
ehat <- matrix(rep(eh, each = p), ncol = p, byrow = TRUE)
ehat

[,1]         [,2]         [,3]         [,4]         [,5]        
 [1,] -0.000984857 -0.000984857 -0.000984857 -0.000984857 -0.000984857
 [2,]  0.471993718  0.471993718  0.471993718  0.471993718  0.471993718
 [3,] -1.005882635 -1.005882635 -1.005882635 -1.005882635 -1.005882635
 [4,] -0.524737426 -0.524737426 -0.524737426 -0.524737426 -0.524737426
 [5,] -1.444355676 -1.444355676 -1.444355676 -1.444355676 -1.444355676
 [6,]  1.610965207  1.610965207  1.610965207  1.610965207  1.610965207
 [7,] -0.362085576 -0.362085576 -0.362085576 -0.362085576 -0.362085576
 [8,]  0.186716429  0.186716429  0.186716429  0.186716429  0.186716429
 [9,]  0.678388275  0.678388275  0.678388275  0.678388275  0.678388275
[10,]  1.654282282  1.654282282  1.654282282  1.654282282  1.654282282

In [36]:
tXtpsi * g

[,1]       [,2]        [,3]         [,4]        [,5]       
 [1,]  0.3637831 -1.55178393  0.138887905  1.76429922  0.66562477
 [2,] -0.3254174 -1.24225464 -0.708552737  0.32855691  0.65083763
 [3,]  0.1577606  0.08048616  0.084684313 -0.15286816  0.02180109
 [4,]  1.0154398 -0.46021252 -1.408066034  0.54257587 -1.02893539
 [5,]  2.8641833  1.27317877 -3.313917327 -2.48579935 -3.32072158
 [6,] -1.2036274 -0.04460076 -1.414027881 -2.00082540 -0.55339966
 [7,] -0.1300836 -0.02902838 -0.018505441 -0.03410578  0.09929198
 [8,] -0.2168479  0.20216717  0.002015686 -0.10680980 -0.26857247
 [9,]  0.3350533 -0.47980302 -0.595854518 -0.08816441  0.65139243
[10,] -0.3265705 -0.46264016 -0.135860158 -0.05426076 -0.01771404

In [37]:
tXtpsi

[,1]       [,2]        [,3]         [,4]       [,5]       
 [1,]  0.4238311 -1.80792985  0.161813501  2.0555241  0.77549642
 [2,]  0.3461468  1.32138734  0.753688161 -0.3494863 -0.69229655
 [3,] -1.2986887 -0.66256392 -0.697123263  1.2584143 -0.17946709
 [4,]  1.3794106 -0.62516953 -1.912768420  0.7370549 -1.39774349
 [5,] -1.2171622 -0.54104956  1.408281016  1.0563643  1.41117255
 [6,]  0.8542974  0.03165623  1.003633148  1.4201238  0.39278592
 [7,]  1.2294922  0.27436336  0.174905243  0.3223528 -0.93846385
 [8,] -0.9540326  0.88944415  0.008868108 -0.4699148 -1.18159745
 [9,]  0.8146575 -1.16660592 -1.448776660 -0.2143653  1.58381302
[10,] -0.9024298 -1.27843849 -0.375429699 -0.1499417 -0.04895017

In [38]:
g

[,1]       [,2]       [,3]       [,4]       [,5]      
 [1,]  0.8583209  0.8583209  0.8583209  0.8583209  0.8583209
 [2,] -0.9401139 -0.9401139 -0.9401139 -0.9401139 -0.9401139
 [3,] -0.1214768 -0.1214768 -0.1214768 -0.1214768 -0.1214768
 [4,]  0.7361404  0.7361404  0.7361404  0.7361404  0.7361404
 [5,] -2.3531648 -2.3531648 -2.3531648 -2.3531648 -2.3531648
 [6,] -1.4089091 -1.4089091 -1.4089091 -1.4089091 -1.4089091
 [7,] -0.1058027 -0.1058027 -0.1058027 -0.1058027 -0.1058027
 [8,]  0.2272961  0.2272961  0.2272961  0.2272961  0.2272961
 [9,]  0.4112811  0.4112811  0.4112811  0.4112811  0.4112811
[10,]  0.3618791  0.3618791  0.3618791  0.3618791  0.3618791

In [34]:
g

[,1]       [,2]       [,3]       [,4]       [,5]      
 [1,]  0.8583209  0.8583209  0.8583209  0.8583209  0.8583209
 [2,] -0.9401139 -0.9401139 -0.9401139 -0.9401139 -0.9401139
 [3,] -0.1214768 -0.1214768 -0.1214768 -0.1214768 -0.1214768
 [4,]  0.7361404  0.7361404  0.7361404  0.7361404  0.7361404
 [5,] -2.3531648 -2.3531648 -2.3531648 -2.3531648 -2.3531648
 [6,] -1.4089091 -1.4089091 -1.4089091 -1.4089091 -1.4089091
 [7,] -0.1058027 -0.1058027 -0.1058027 -0.1058027 -0.1058027
 [8,]  0.2272961  0.2272961  0.2272961  0.2272961  0.2272961
 [9,]  0.4112811  0.4112811  0.4112811  0.4112811  0.4112811
[10,]  0.3618791  0.3618791  0.3618791  0.3618791  0.3618791