In [13]:
# !pip install numpy scikit-learn seaborn matplotlib
import pandas as pd
import numpy as np
import itertools
from matplotlib import pyplot as plt
from sklearn.linear_model import LinearRegression 
import warnings
warnings.filterwarnings("ignore")

## 1. DATA ANALYSIS

1. Import the data set. Make sure the column names are imported as intended.

In [14]:
# Data
data = pd.read_csv('../Assignment_1/wage2015_subsample_inference.csv')
display(data.head())
# display(data.tail())
display(data.info())
display(data.columns)
display(data.shape)

rownames       wage     lwage  sex  shs  hsg  scl  clg   ad   mw  ...   we  \
0        10   9.615385  2.263364  1.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0   
1        12  48.076923  3.872802  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0   
2        15  11.057692  2.403126  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0   
3        18  13.942308  2.634928  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0   
4        19  28.846154  3.361977  1.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0   

    ne  exp1  exp2    exp3     exp4     occ  occ2     ind  ind2  
0  1.0   7.0  0.49   0.343   0.2401  3600.0    11  8370.0    18  
1  1.0  31.0  9.61  29.791  92.3521  3050.0    10  5070.0     9  
2  1.0  18.0  3.24   5.832  10.4976  6260.0    19   770.0     4  
3  1.0  25.0  6.25  15.625  39.0625   420.0     1  6990.0    12  
4  1.0  22.0  4.84  10.648  23.4256  2015.0     6  9470.0    22  

[5 rows x 21 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5150 entries, 0 to 5149
Data columns (total 21 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   rownames  5150 non-null   int64  
 1   wage      5150 non-null   float64
 2   lwage     5150 non-null   float64
 3   sex       5150 non-null   float64
 4   shs       5150 non-null   float64
 5   hsg       5150 non-null   float64
 6   scl       5150 non-null   float64
 7   clg       5150 non-null   float64
 8   ad        5150 non-null   float64
 9   mw        5150 non-null   float64
 10  so        5150 non-null   float64
 11  we        5150 non-null   float64
 12  ne        5150 non-null   float64
 13  exp1      5150 non-null   float64
 14  exp2      5150 non-null   float64
 15  exp3      5150 non-null   float64
 16  exp4      5150 non-null   float64
 17  occ       5150 non-null   float64
 18  occ2      5150 non-null   int64  
 19  ind       5150 non-null   float64
 20  ind2      5150 non-null   int6

None

Index(['rownames', 'wage', 'lwage', 'sex', 'shs', 'hsg', 'scl', 'clg', 'ad',
       'mw', 'so', 'we', 'ne', 'exp1', 'exp2', 'exp3', 'exp4', 'occ', 'occ2',
       'ind', 'ind2'],
      dtype='object')

(5150, 21)

2. Are there missing values? Display the number of missings (if any) of each variable in the data set.


In [15]:
missing_values = data.isnull().sum()
print(missing_values)
# No hay missings en el dataframe

rownames    0
wage        0
lwage       0
sex         0
shs         0
hsg         0
scl         0
clg         0
ad          0
mw          0
so          0
we          0
ne          0
exp1        0
exp2        0
exp3        0
exp4        0
occ         0
occ2        0
ind         0
ind2        0
dtype: int64


3. Report descriptive statistics of the variables (mean, standard deviation, percentiles, etc.). Interpret your results.

In [16]:
data.describe().T
# FALTA INTERPRETAS

count          mean           std         min          25%  \
rownames  5150.0  15636.346602   9700.744395   10.000000  7132.500000   
wage      5150.0     23.410410     21.003016    3.021978    13.461538   
lwage     5150.0      2.970787      0.570385    1.105912     2.599837   
sex       5150.0      0.444466      0.496955    0.000000     0.000000   
shs       5150.0      0.023301      0.150872    0.000000     0.000000   
hsg       5150.0      0.243883      0.429465    0.000000     0.000000   
scl       5150.0      0.278058      0.448086    0.000000     0.000000   
clg       5150.0      0.317670      0.465616    0.000000     0.000000   
ad        5150.0      0.137087      0.343973    0.000000     0.000000   
mw        5150.0      0.259612      0.438464    0.000000     0.000000   
so        5150.0      0.296505      0.456761    0.000000     0.000000   
we        5150.0      0.216117      0.411635    0.000000     0.000000   
ne        5150.0      0.227767      0.419432    0.000000     0.000000   
exp1      5150.0     13.760583     10.609465    0.000000     5.000000   
exp2      5150.0      3.018925      4.000904    0.000000     0.250000   
exp3      5150.0      8.235867     14.488962    0.000000     0.125000   
exp4      5150.0     25.118038     53.530225    0.000000     0.062500   
occ       5150.0   5310.737476  11874.356080   10.000000  1740.000000   
occ2      5150.0     11.670874      6.966684    1.000000     5.000000   
ind       5150.0   6629.154951   5333.443992  370.000000  4880.000000   
ind2      5150.0     13.316893      5.701019    2.000000     9.000000   

                   50%           75%            max  
rownames  15260.000000  24337.750000   32643.000000  
wage         19.230769     27.777778     528.845673  
lwage         2.956512      3.324236       6.270697  
sex           0.000000      1.000000       1.000000  
shs           0.000000      0.000000       1.000000  
hsg           0.000000      0.000000       1.000000  
scl           0.000000      1.000000       1.000000  
clg           0.000000      1.000000       1.000000  
ad            0.000000      0.000000       1.000000  
mw            0.000000      1.000000       1.000000  
so            0.000000      1.000000       1.000000  
we            0.000000      0.000000       1.000000  
ne            0.000000      0.000000       1.000000  
exp1         10.000000     21.000000      47.000000  
exp2          1.000000      4.410000      22.090000  
exp3          1.000000      9.261000     103.823000  
exp4          1.000000     19.448100     487.968100  
occ        4040.000000   5610.000000  100000.000000  
occ2         13.000000     17.000000      22.000000  
ind        7370.000000   8190.000000  100000.000000  
ind2         14.000000     18.000000      22.000000

4. How many women with a college graduate degree (clg) or above have a wage corresponding to the 25% richest of the sample? Report the dataframe corresponding to this conditions and the result.

In [17]:
# 25% richest of the sample
richest = data['wage'].quantile(0.75)

# Mujeres con título universitario o superior
data_mujeres = data.loc[(data['sex'] == 1) & 
                                ((data['clg'] == 1) | (data['ad'] == 1))]

# Filtrar mujeres cuyo salario esté en el 25% superior
data_mujeres_ricas = data_mujeres.loc[data_mujeres['wage'] >= richest]

# Mujeres con título universitario o superior que ganan por encima del percentil 75
num_mujeres_ricas = len(data_mujeres_ricas)

print(data_mujeres_ricas)
print(f'Número de mujeres con título universitario o superior que pertenecen al 25% más rico: {num_mujeres_ricas}')


      rownames        wage     lwage  sex  shs  hsg  scl  clg   ad   mw  ...  \
4           19   28.846154  3.361977  1.0  0.0  0.0  0.0  1.0  0.0  0.0  ...   
30         191   42.307692  3.744969  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...   
39         232   41.208791  3.718652  1.0  0.0  0.0  0.0  1.0  0.0  0.0  ...   
54         319  100.000000  4.605170  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...   
91         563   33.653846  3.516127  1.0  0.0  0.0  0.0  1.0  0.0  0.0  ...   
...        ...         ...       ...  ...  ...  ...  ...  ...  ...  ...  ...   
5085     32251   48.076923  3.872802  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...   
5093     32314   30.145530  3.406037  1.0  0.0  0.0  0.0  1.0  0.0  0.0  ...   
5105     32419   29.914530  3.398344  1.0  0.0  0.0  0.0  1.0  0.0  0.0  ...   
5131     32567   48.076923  3.872802  1.0  0.0  0.0  0.0  1.0  0.0  0.0  ...   
5140     32596   45.546559  3.818735  1.0  0.0  0.0  0.0  1.0  0.0  0.0  ...   

       we   ne  exp1   exp2    exp3    

In [18]:
print(data.sex.value_counts())
num_mujeres=data['sex'].sum()
print(num_mujeres)
num_mujeres_tit = len(data_mujeres)
print(num_mujeres_tit)
# el total de mujeres es 2289
# las mujeres que tiene título o superior son 1196
porcentaje_total = (num_mujeres_ricas / num_mujeres)*100
porcentaje_tituladas=(num_mujeres_ricas / num_mujeres_tit)*100
print(porcentaje_total)
print(porcentaje_tituladas)

print(f'El porcentaje sobre el total de mujeres es: {porcentaje_total}')
print(f'El porcentaje sobre el total de mujeres tituladas o con un nivel mayor: {porcentaje_tituladas}')

sex
0.0    2861
1.0    2289
Name: count, dtype: int64
2289.0
1196
18.304936653560507
35.03344481605351
El porcentaje sobre el total de mujeres es: 18.304936653560507
El porcentaje sobre el total de mujeres tituladas o con un nivel mayor: 35.03344481605351


5. How many men with a high school graduate degree (hsg) or below have a wage corresponding to the 25% richest of the sample? Report the dataframe corresponding to this conditions and the result.

In [19]:
# 25% richest of the sample
richest = data['wage'].quantile(0.75)

# Mujeres con título universitario o superior
data_hombres = data.loc[(data['sex'] == 0) & 
                                ((data['shs'] == 1) | (data['hsg'] == 1))]

# Filtrar mujeres cuyo salario esté en el 25% superior
data_hombres_ricos = data_hombres.loc[data_hombres['wage'] >= richest]

# Mujeres con título universitario o superior que ganan por encima del percentil 75
num_hombres_ricos = len(data_hombres_ricos)

print(data_hombres_ricos)
print(f'Número de hombres que se graduaron de highschool o con un grado menor que pertenecen al 25% más rico: {num_hombres_ricos}')


      rownames       wage     lwage  sex  shs  hsg  scl  clg   ad   mw  ...  \
15         113  27.884615  3.328075  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...   
46         276  28.846154  3.361977  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...   
75         467  28.846154  3.361977  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...   
136        858  28.846154  3.361977  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...   
140        876  29.714286  3.391628  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...   
...        ...        ...       ...  ...  ...  ...  ...  ...  ...  ...  ...   
5074     32191  33.653846  3.516127  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...   
5086     32254  40.865385  3.710283  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...   
5089     32281  31.250000  3.442019  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...   
5094     32321  33.653846  3.516127  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...   
5148     32631  32.967033  3.495508  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...   

       we   ne  exp1   exp2    exp3      exp4     o

Son 118 hombres que se graduaron de highschool o con un grado menor los que forman parte del 25% más rico de la muestra.

In [20]:
print(data.sex.value_counts())
num_hombres= len(data) - data['sex'].sum()
print(num_hombres)
num_hombres_hsg = len(data_hombres)
print(num_hombres_hsg)
# el total de hombres es 2861
# los hombres que se graduaron de highschool o con un nivel menor son 933
porcentaje_total = (num_hombres_ricos / num_hombres)*100
porcentaje_hsg=(num_hombres_ricos / num_hombres_hsg)*100
print(f'El porcentaje sobre el total de hombres es: {porcentaje_total}')
print(f'El porcentaje sobre el total de hombres con nivel seccundario o menor es: {porcentaje_hsg}')

sex
0.0    2861
1.0    2289
Name: count, dtype: int64
2861.0
933
El porcentaje sobre el total de hombres es: 4.124432016777351
El porcentaje sobre el total de hombres con nivel seccundario o menor es: 12.64737406216506


6. Create two dataframes. One containing only the log(wage) and the other containig every variable of the data set but the wage related variables.

In [36]:
salario = data[['lwage']]
sin_salario = data.drop(columns=['lwage', 'wage'])

## 2. Data wrangling

7. Make an array for our $Y $ variable, which will be the logarithm of wage (lwage column)

In [37]:
Y = data['lwage'].values
Y_matrix = Y.reshape(-1, 1)
print("Matriz para la variable Y (logaritmo del salario):")
print(Y_matrix)


Matriz para la variable Y (logaritmo del salario):
[[2.26336438]
 [3.87280229]
 [2.40312632]
 ...
 [3.64965874]
 [3.49550806]
 [2.85115104]]


8. Make three new arrays for our predictors:

8.1. The basic model will have the columns sex hsg scl clg ad so we ne exp1 occ2 ind2. Make sure to convert occ2 and ind2 to dummies and to drop the first dummy value to prevent multicolinearity. 

$
\text{sex} + \text{exp1} + \text{hsg} + \text{scl} + \text{clg} + \text{ad} + \text{so} + \text{we} + \text{ne} + \text{dummy(occ2)} + \text{dummy(ind2)}
$

In [38]:
# Obtenermos las dummies
predictors = sin_salario[['sex', 'hsg', 'scl', 'clg', 'ad', 'so', 'we', 'ne', 'exp1', 'occ2', 'ind2']]
predictors = pd.get_dummies(predictors, columns=['occ2', 'ind2'],  drop_first=True, dtype=int)
#display(predictors.head())
# display(data.tail())
# display(predictors.info())
display(predictors.columns)
display(predictors.shape)

Index(['sex', 'hsg', 'scl', 'clg', 'ad', 'so', 'we', 'ne', 'exp1', 'occ2_2',
       'occ2_3', 'occ2_4', 'occ2_5', 'occ2_6', 'occ2_7', 'occ2_8', 'occ2_9',
       'occ2_10', 'occ2_11', 'occ2_12', 'occ2_13', 'occ2_14', 'occ2_15',
       'occ2_16', 'occ2_17', 'occ2_18', 'occ2_19', 'occ2_20', 'occ2_21',
       'occ2_22', 'ind2_3', 'ind2_4', 'ind2_5', 'ind2_6', 'ind2_7', 'ind2_8',
       'ind2_9', 'ind2_10', 'ind2_11', 'ind2_12', 'ind2_13', 'ind2_14',
       'ind2_15', 'ind2_16', 'ind2_17', 'ind2_18', 'ind2_19', 'ind2_20',
       'ind2_21', 'ind2_22'],
      dtype='object')

(5150, 50)

In [39]:
# Convertir el DataFrame a un array NumPy
predictors_array = predictors.to_numpy()

# Mostrar el array para verificar
print(predictors_array)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


8.2. The flexible model will have the same columns, and will also include polynomials for experience (exp2 exp3 exp4), as well as the interactions between all experience variables and other variables except for sex. 

Hint: you can use a for loop to multiply the desired variables and create the interactions. Some packages might also have ways to easily specify the model variables with strings like R does by default

$
\text{sex} + \text{exp1} + \text{exp2} + \text{exp3} + \text{exp4} +
\text{hsg} + \text{scl} + \text{clg} + \text{ad} + \text{so} + 
\text{we} + \text{ne} + \text{dummy(occ2)} + \text{dummy(ind2)} +
\left( \text{exp1} + \text{exp2} + \text{exp3} + \text{exp4} \right) \times 
\left( \text{hsg} + \text{scl} + \text{clg} + \text{ad} + \text{so} + 
\text{we} + \text{ne} + \text{dummy(occ2)} + \text{dummy(ind2)} \right)
$

In [40]:
#variables
predictors_2 = sin_salario[['sex', 'exp1', 'exp2', 'exp3', 'exp4','hsg', 'scl', 'clg', 'ad', 'so', 'we', 'ne', 'occ2', 'ind2']]
#obtenemos dummies
predictors_2 = pd.get_dummies(predictors_2, columns=['occ2', 'ind2'], drop_first=True, dtype=int)

# suma se exp1 + ... exp4
predictors_2['exp'] = predictors_2[['exp1', 'exp2', 'exp3', 'exp4']].sum(axis=1)
# suma de las demas variables expeto las dummies y sex
predictors_2['suma'] = predictors_2[['hsg', 'scl', 'clg', 'ad', 'so', 'we', 'ne']].sum(axis=1)
# suma de dummies
dummy_columns = [col for col in predictors_2.columns if col.startswith('occ2_') or col.startswith('ind2_')]
predictors_2['dummy_sum'] = predictors_2[dummy_columns].sum(axis=1)

# suma de la sum de dummies de occ2 y ind2, con la suma de las demás variables
predictors_2['sum_2'] = predictors_2[['suma', 'dummy_sum']].sum(axis=1)

# variable de interacción
predictors_2['interaction'] = predictors_2['exp'] * predictors_2['sum_2']

#elimino variables que se usaron para obtener la variable de interacción
predictors_2 = predictors_2.drop(columns=['exp','suma', 'dummy_sum','sum_2'])

display(predictors_2.columns)
display(predictors_2.shape)

Index(['sex', 'exp1', 'exp2', 'exp3', 'exp4', 'hsg', 'scl', 'clg', 'ad', 'so',
       'we', 'ne', 'occ2_2', 'occ2_3', 'occ2_4', 'occ2_5', 'occ2_6', 'occ2_7',
       'occ2_8', 'occ2_9', 'occ2_10', 'occ2_11', 'occ2_12', 'occ2_13',
       'occ2_14', 'occ2_15', 'occ2_16', 'occ2_17', 'occ2_18', 'occ2_19',
       'occ2_20', 'occ2_21', 'occ2_22', 'ind2_3', 'ind2_4', 'ind2_5', 'ind2_6',
       'ind2_7', 'ind2_8', 'ind2_9', 'ind2_10', 'ind2_11', 'ind2_12',
       'ind2_13', 'ind2_14', 'ind2_15', 'ind2_16', 'ind2_17', 'ind2_18',
       'ind2_19', 'ind2_20', 'ind2_21', 'ind2_22', 'interaction'],
      dtype='object')

(5150, 54)

In [41]:
predictors_2

sex  exp1  exp2    exp3     exp4  hsg  scl  clg   ad   so  ...  ind2_14  \
0     1.0   7.0  0.49   0.343   0.2401  0.0  0.0  1.0  0.0  0.0  ...        0   
1     0.0  31.0  9.61  29.791  92.3521  0.0  0.0  1.0  0.0  0.0  ...        0   
2     0.0  18.0  3.24   5.832  10.4976  1.0  0.0  0.0  0.0  0.0  ...        0   
3     1.0  25.0  6.25  15.625  39.0625  0.0  0.0  0.0  1.0  0.0  ...        0   
4     1.0  22.0  4.84  10.648  23.4256  0.0  0.0  1.0  0.0  0.0  ...        0   
...   ...   ...   ...     ...      ...  ...  ...  ...  ...  ...  ...      ...   
5145  0.0   9.0  0.81   0.729   0.6561  0.0  0.0  1.0  0.0  0.0  ...        0   
5146  1.0  12.0  1.44   1.728   2.0736  0.0  1.0  0.0  0.0  0.0  ...        0   
5147  0.0  11.0  1.21   1.331   1.4641  0.0  0.0  0.0  1.0  0.0  ...        0   
5148  0.0  10.0  1.00   1.000   1.0000  1.0  0.0  0.0  0.0  0.0  ...        0   
5149  0.0  14.0  1.96   2.744   3.8416  0.0  0.0  0.0  1.0  0.0  ...        1   

      ind2_15  ind2_16  ind2_17  ind2_18  ind2_19  ind2_20  ind2_21  ind2_22  \
0           0        0        0        1        0        0        0        0   
1           0        0        0        0        0        0        0        0   
2           0        0        0        0        0        0        0        0   
3           0        0        0        0        0        0        0        0   
4           0        0        0        0        0        0        0        1   
...       ...      ...      ...      ...      ...      ...      ...      ...   
5145        0        0        0        0        0        0        0        0   
5146        0        0        0        0        0        1        0        0   
5147        0        0        0        0        0        0        0        0   
5148        0        0        0        0        0        0        0        0   
5149        0        0        0        0        0        0        0        0   

      interaction  
0         32.2924  
1        651.0124  
2        150.2784  
3        257.8125  
4        243.6544  
...           ...  
5145      44.7804  
5146      68.9664  
5147      60.0204  
5148      52.0000  
5149      90.1824  

[5150 rows x 54 columns]

In [42]:
# Convertir el DataFrame a un array NumPy
predictors2_array = predictors_2.to_numpy()

# Mostrar las columnas del DataFrame final
print("Columnas del DataFrame final:")
print(predictors_2.columns)

# Mostrar el contenido del array NumPy
print("Contenido del array NumPy:")
print(predictors2_array)

# Mostrar la forma del array NumPy
print("Forma del array NumPy:")
print(predictors2_array.shape)


Columnas del DataFrame final:
Index(['sex', 'exp1', 'exp2', 'exp3', 'exp4', 'hsg', 'scl', 'clg', 'ad', 'so',
       'we', 'ne', 'occ2_2', 'occ2_3', 'occ2_4', 'occ2_5', 'occ2_6', 'occ2_7',
       'occ2_8', 'occ2_9', 'occ2_10', 'occ2_11', 'occ2_12', 'occ2_13',
       'occ2_14', 'occ2_15', 'occ2_16', 'occ2_17', 'occ2_18', 'occ2_19',
       'occ2_20', 'occ2_21', 'occ2_22', 'ind2_3', 'ind2_4', 'ind2_5', 'ind2_6',
       'ind2_7', 'ind2_8', 'ind2_9', 'ind2_10', 'ind2_11', 'ind2_12',
       'ind2_13', 'ind2_14', 'ind2_15', 'ind2_16', 'ind2_17', 'ind2_18',
       'ind2_19', 'ind2_20', 'ind2_21', 'ind2_22', 'interaction'],
      dtype='object')
Contenido del array NumPy:
[[1.000000e+00 7.000000e+00 4.900000e-01 ... 0.000000e+00 0.000000e+00
  3.229240e+01]
 [0.000000e+00 3.100000e+01 9.610000e+00 ... 0.000000e+00 0.000000e+00
  6.510124e+02]
 [0.000000e+00 1.800000e+01 3.240000e+00 ... 0.000000e+00 0.000000e+00
  1.502784e+02]
 ...
 [0.000000e+00 1.100000e+01 1.210000e+00 ... 0.000000e+00 0.000

In [43]:
predictors2_array

array([[1.000000e+00, 7.000000e+00, 4.900000e-01, ..., 0.000000e+00,
        0.000000e+00, 3.229240e+01],
       [0.000000e+00, 3.100000e+01, 9.610000e+00, ..., 0.000000e+00,
        0.000000e+00, 6.510124e+02],
       [0.000000e+00, 1.800000e+01, 3.240000e+00, ..., 0.000000e+00,
        0.000000e+00, 1.502784e+02],
       ...,
       [0.000000e+00, 1.100000e+01, 1.210000e+00, ..., 0.000000e+00,
        0.000000e+00, 6.002040e+01],
       [0.000000e+00, 1.000000e+01, 1.000000e+00, ..., 0.000000e+00,
        0.000000e+00, 5.200000e+01],
       [0.000000e+00, 1.400000e+01, 1.960000e+00, ..., 0.000000e+00,
        0.000000e+00, 9.018240e+01]])

8.3. The extra-flexible model will include all two-way interactions between variables, except for sex. 

Hint: If you use a for loop here, you might create several variables identical to others. You can make another procedure to get rid of duplicates

$
\text{sex} + \left( \text{exp1} + \text{exp2} + \text{exp3} + \text{exp4} + \text{hsg} + \text{scl} + \text{clg} + \text{ad} + \text{so} + \text{we} + \text{ne} + \text{dummy(occ2)} + \text{dummy(ind2)} \right)^2
$

In [44]:
#variables
predictors_3 = sin_salario[['sex', 'exp1', 'exp2', 'exp3', 'exp4','hsg', 'scl', 'clg', 'ad', 'so', 'we', 'ne', 'occ2', 'ind2']]
#obtenemos dummies
predictors_3 = pd.get_dummies(predictors_3, columns=['occ2', 'ind2'], drop_first=True, dtype=int)

# Todas las columnas excepto 'sex'
columns_to_include = [col for col in predictors_3.columns if col != 'sex']

# suma de todas las variables seleccionadas
predictors_3['sum_vars'] = predictors_3[columns_to_include].sum(axis=1)

# Nueva variable:cuadrado de la suma de todas las variables
predictors_3['sum_vars_squared'] = predictors_3['sum_vars'] ** 2

display(predictors_3.head())

sex  exp1  exp2    exp3     exp4  hsg  scl  clg   ad   so  ...  ind2_15  \
0  1.0   7.0  0.49   0.343   0.2401  0.0  0.0  1.0  0.0  0.0  ...        0   
1  0.0  31.0  9.61  29.791  92.3521  0.0  0.0  1.0  0.0  0.0  ...        0   
2  0.0  18.0  3.24   5.832  10.4976  1.0  0.0  0.0  0.0  0.0  ...        0   
3  1.0  25.0  6.25  15.625  39.0625  0.0  0.0  0.0  1.0  0.0  ...        0   
4  1.0  22.0  4.84  10.648  23.4256  0.0  0.0  1.0  0.0  0.0  ...        0   

   ind2_16  ind2_17  ind2_18  ind2_19  ind2_20  ind2_21  ind2_22  sum_vars  \
0        0        0        1        0        0        0        0   12.0731   
1        0        0        0        0        0        0        0  166.7531   
2        0        0        0        0        0        0        0   41.5696   
3        0        0        0        0        0        0        0   88.9375   
4        0        0        0        0        0        0        1   64.9136   

   sum_vars_squared  
0        145.759744  
1      27806.596360  
2       1728.031644  
3       7909.878906  
4       4213.775465  

[5 rows x 55 columns]

In [45]:
# Convertir el DataFrame a un array NumPy
predictors3_array = predictors_3.to_numpy()

# Mostrar las columnas del DataFrame final
print("Columnas del DataFrame final:")
print(predictors_3.columns)

# Mostrar el contenido del array NumPy
print("Contenido del array NumPy:")
print(predictors3_array)

# Mostrar la forma del array NumPy
print("Forma del array NumPy:")
print(predictors3_array.shape)

Columnas del DataFrame final:
Index(['sex', 'exp1', 'exp2', 'exp3', 'exp4', 'hsg', 'scl', 'clg', 'ad', 'so',
       'we', 'ne', 'occ2_2', 'occ2_3', 'occ2_4', 'occ2_5', 'occ2_6', 'occ2_7',
       'occ2_8', 'occ2_9', 'occ2_10', 'occ2_11', 'occ2_12', 'occ2_13',
       'occ2_14', 'occ2_15', 'occ2_16', 'occ2_17', 'occ2_18', 'occ2_19',
       'occ2_20', 'occ2_21', 'occ2_22', 'ind2_3', 'ind2_4', 'ind2_5', 'ind2_6',
       'ind2_7', 'ind2_8', 'ind2_9', 'ind2_10', 'ind2_11', 'ind2_12',
       'ind2_13', 'ind2_14', 'ind2_15', 'ind2_16', 'ind2_17', 'ind2_18',
       'ind2_19', 'ind2_20', 'ind2_21', 'ind2_22', 'sum_vars',
       'sum_vars_squared'],
      dtype='object')
Contenido del array NumPy:
[[1.00000000e+00 7.00000000e+00 4.90000000e-01 ... 0.00000000e+00
  1.20731000e+01 1.45759744e+02]
 [0.00000000e+00 3.10000000e+01 9.61000000e+00 ... 0.00000000e+00
  1.66753100e+02 2.78065964e+04]
 [0.00000000e+00 1.80000000e+01 3.24000000e+00 ... 0.00000000e+00
  4.15696000e+01 1.72803164e+03]
 ...
 [0

9. Normalize all the variables, including $Y$. This means that for each variable $V$, create $\tilde{V}$ such that

$
\tilde{V} = \frac{V - \text{mean}(V)}{\text{sd}(V)}
$

In [46]:
# Dataframe normalizada
normalized_data = data.copy()
# Normalizar todas las columnas numéricas
for column in normalized_data.select_dtypes(include=['float64', 'int64']).columns:
    mean = normalized_data[column].mean()
    std_dev = normalized_data[column].std()
    normalized_data[column] = (normalized_data[column] - mean) / std_dev

# Verificar el DataFrame normalizado
print(normalized_data.head())

   rownames      wage     lwage       sex       shs       hsg       scl  \
0 -1.610840 -0.656812 -1.240255  1.117877 -0.154442 -0.567878 -0.620547   
1 -1.610634  1.174427  1.581416 -0.894379 -0.154442 -0.567878 -0.620547   
2 -1.610325 -0.588140 -0.995224 -0.894379 -0.154442  1.760601 -0.620547   
3 -1.610015 -0.450797 -0.588828  1.117877 -0.154442 -0.567878 -0.620547   
4 -1.609912  0.258808  0.685835  1.117877 -0.154442 -0.567878 -0.620547   

        clg        ad        mw  ...       we        ne      exp1      exp2  \
0  1.465437 -0.398541 -0.592093  ... -0.52502  1.841139 -0.637222 -0.632088   
1  1.465437 -0.398541 -0.592093  ... -0.52502  1.841139  1.624909  1.647396   
2 -0.682258 -0.398541 -0.592093  ... -0.52502  1.841139  0.399588  0.055256   
3 -0.682258  2.508664 -0.592093  ... -0.52502  1.841139  1.059376  0.807586   
4  1.465437 -0.398541 -0.592093  ... -0.52502  1.841139  0.776610  0.455166   

       exp3      exp4       occ      occ2       ind      ind2  
0 -0.54475

In [47]:
# Y = tasa salarial por hora (log)
# X = {ingresos anuales, número total de horas trabajadas} 
# número total de horas trabajadas = número de semanas trabajadas * número habitual de horas trabajadas por semana} 

## Linear Regressions

10. Split each of the dataframes created (basic, flexible and extra-flexible models) into a training sample (80% of the data) and a test sample. Use the normalized data for this. Hint: You do not need to normalize the data for dummy variables.

11. Estimate all three models

* basic

* flexible

* extra-flexible model

12. Report the MSE and the $R^2$ for both samples of each model, and the $ \text{adjusted}  \ R^2 $ for the training sample. Do we see overfitting? Which model has the best out-of-sample performance?