In [1]:
using RData, LinearAlgebra, GLM, DataFrames, Statistics, Random, Distributions,
DataStructures, NamedArrays, PrettyTables, StatsModels, Combinatorics, Plots, Metrics

## 1. Multicollinearity

In [2]:
m=10
n=10
A=zeros(m,n)

for i in 1:(n-1)
    temp = randn(10)
    A[:,i] = temp
end

In [3]:
A[:,10] = 0.5*A[:,1]+ 0.5*A[:,2]
A

10×10 Matrix{Float64}:
  0.501424   2.33014   -0.588513   …   0.33932      0.902817   1.41578
  0.229565   0.496142  -0.690482      -0.199448     0.577443   0.362853
  1.26491   -0.489678   0.524373      -1.04054     -0.394571   0.387618
  1.34268   -0.370234  -0.640244       0.403512     1.00102    0.486222
  0.123511  -1.46896   -0.480382       1.15467      2.86276   -0.672722
 -1.56356    0.795115   0.49276    …  -0.0550964   -0.155911  -0.384221
  0.123536  -0.900076  -0.157412      -2.90485     -0.761958  -0.38827
  1.31983    2.5552     0.0759475      0.126657     1.24901    1.93751
 -0.627868  -1.21785   -1.73209        0.312876    -1.42755   -0.922859
  0.28068    1.09421   -0.58454        0.00273404   0.865664   0.687444

In [4]:
inv(A)

10×10 Matrix{Float64}:
  1.82653e15  -8.66904e14   1.53059e15  …   6.06548e14  -2.71182e14
  1.82653e15  -8.66904e14   1.53059e15      6.06548e14  -2.71182e14
 -0.322614     0.2241      -0.032776       -0.475945    -0.107604
  3.41651     -0.796798     0.219773       -1.14961      0.530822
 -0.292802     0.200186     0.111385        0.174155    -0.270638
 -0.340136    -0.110503     0.251844    …   0.259735     0.0304348
 -1.02324      0.378217     0.11807         0.335001    -0.011283
 -1.22617      0.3783       0.0198841       0.551687    -0.560248
  1.25823     -0.359622    -0.0415768      -0.580098     0.402005
 -3.65306e15   1.73381e15  -3.06118e15     -1.2131e15    5.42363e14

## Analyzing RCT data with Precision Adjustment

In [5]:
mat, head = readdlm("../../../data/penn_jae.dat", header=true, Float64)
mat
df =DataFrame(mat, vec(head))

23×7 DataFrame
 Row │ variable    mean            min      median   max      nmissing  eltype ⋯
     │ Symbol      Float64         Float64  Float64  Float64  Int64     DataTy ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ abdt        10693.6         10404.0  10691.0  10880.0         0  Float6 ⋯
   2 │ tg              2.56889         0.0      2.0      6.0         0  Float6
   3 │ inuidur1       12.9148          1.0     10.0     52.0         0  Float6
   4 │ inuidur2       12.1938          0.0      9.0     52.0         0  Float6
   5 │ female          0.402142        0.0      0.0      1.0         0  Float6 ⋯
   6 │ black           0.116653        0.0      0.0      1.0         0  Float6
   7 │ hispanic        0.0363689       0.0      0.0      1.0         0  Float6
   8 │ othrace         0.00575002      0.0      0.0      1.0         0  Float6
   9 │ dep             0.444045        0.0      0.0      2.0         0  Float6 ⋯
  10 │ q1              0.0136563       0.0      0.0      1.0         0  Float6
  11 │ q2              0.206498        0.0      0.0      1.0         0  Float6
  ⋮  │     ⋮             ⋮            ⋮        ⋮        ⋮        ⋮         ⋮   ⋱
  14 │ q5              0.232948        0.0      0.0      1.0         0  Float6
  15 │ q6              0.0769784       0.0      0.0      1.0         0  Float6 ⋯
  16 │ recall          0.108675        0.0      0.0      1.0         0  Float6
  17 │ agelt35         0.543089        0.0      1.0      1.0         0  Float6
  18 │ agegt54         0.106735        0.0      0.0      1.0         0  Float6
  19 │ durable         0.148638        0.0      0.0      1.0         0  Float6 ⋯
  20 │ nondurable      0.10961         0.0      0.0      1.0         0  Float6
  21 │ lusd            0.265435        0.0      0.0      1.0         0  Float6
  22 │ husd            0.221807        0.0      0.0      1.0         0  Float6
  23 │ muld            0.438008        0.0      0.0      1.0         0  Float6 ⋯
                                                     1 column and 2 rows omitted

In [7]:
# Filter control group and just treatment group number 2

penn = filter(row -> row[:tg] in [2,0], df)

first(penn,20)

20×23 DataFrame
 Row │ abdt     tg       inuidur1  inuidur2  female   black    hispanic  othra ⋯
     │ Float64  Float64  Float64   Float64   Float64  Float64  Float64   Float ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ 10824.0      0.0      18.0      18.0      0.0      0.0       0.0      0 ⋯
   2 │ 10635.0      2.0       7.0       3.0      0.0      0.0       0.0      0
   3 │ 10824.0      0.0       1.0       1.0      0.0      0.0       0.0      0
   4 │ 10747.0      0.0      27.0      27.0      0.0      0.0       0.0      0
   5 │ 10754.0      2.0      20.0      20.0      1.0      0.0       0.0      0 ⋯
   6 │ 10831.0      0.0      27.0      27.0      0.0      0.0       0.0      0
   7 │ 10845.0      0.0      27.0      27.0      1.0      0.0       0.0      0
   8 │ 10831.0      0.0       9.0       9.0      1.0      0.0       0.0      0
   9 │ 10859.0      0.0      27.0      27.0      1.0      0.0       0.0      0 ⋯
  10 │ 10628.0      2.0      27.0      27.0      0.0      0.0       0.0      0
  11 │ 10516.0      0.0      15.0      15.0      1.0      0.0       0.0      0
  12 │ 10803.0      2.0       3.0       3.0      1.0      0.0       0.0      0
  13 │ 10663.0      0.0      28.0      11.0      1.0      0.0       0.0      0 ⋯
  14 │ 10747.0      0.0      12.0      12.0      1.0      0.0       0.0      0
  15 │ 10635.0      2.0      17.0      10.0      1.0      0.0       0.0      0
  16 │ 10761.0      2.0      13.0      13.0      0.0      0.0       0.0      0
  17 │ 10768.0      0.0      18.0      18.0      1.0      0.0       0.0      0 ⋯
  18 │ 10537.0      0.0       1.0       1.0      1.0      0.0       0.0      0
  19 │ 10789.0      2.0      34.0       7.0      0.0      0.0       0.0      0
  20 │ 10775.0      2.0      11.0      11.0      0.0      0.0       0.0      0
                                                              16 columns omitted

In [8]:
replace!(penn.tg, 2 => 1)


rename!(penn, "tg" => "T2")


# from float to string
penn[!,:dep] = string.(penn[!,:dep]) 

# dep varaible in categorical format 
penn[!,:dep] = categorical(penn[!,:dep])

describe(penn)

23×7 DataFrame
 Row │ variable    mean        min      median   max      nmissing  eltype     ⋯
     │ Symbol      Union…      Any      Union…   Any      Int64     DataType   ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ abdt        10696.4     10404.0  10698.0  10880.0         0  Float64    ⋯
   2 │ T2          0.419924    0.0      0.0      1.0             0  Float64
   3 │ inuidur1    13.0334     1.0      11.0     52.0            0  Float64
   4 │ inuidur2    12.2511     0.0      10.0     52.0            0  Float64
   5 │ female      0.400726    0.0      0.0      1.0             0  Float64    ⋯
   6 │ black       0.118817    0.0      0.0      1.0             0  Float64
   7 │ hispanic    0.0363196   0.0      0.0      1.0             0  Float64
   8 │ othrace     0.00518852  0.0      0.0      1.0             0  Float64
   9 │ dep                     0.0               2.0             0  Categorica ⋯
  10 │ q1          0.0126254   0.0      0.0      1.0             0  Float64
  11 │ q2          0.200104    0.0      0.0      1.0             0  Float64
  ⋮  │     ⋮           ⋮          ⋮        ⋮        ⋮        ⋮                 ⋱
  14 │ q5          0.263231    0.0      0.0      1.0             0  Float64
  15 │ q6          0.0652024   0.0      0.0      1.0             0  Float64    ⋯
  16 │ recall      0.106192    0.0      0.0      1.0             0  Float64
  17 │ agelt35     0.540125    0.0      1.0      1.0             0  Float64
  18 │ agegt54     0.106019    0.0      0.0      1.0             0  Float64
  19 │ durable     0.149602    0.0      0.0      1.0             0  Float64    ⋯
  20 │ nondurable  0.109132    0.0      0.0      1.0             0  Float64
  21 │ lusd        0.262193    0.0      0.0      1.0             0  Float64
  22 │ husd        0.222068    0.0      0.0      1.0             0  Float64
  23 │ muld        0.440332    0.0      0.0      1.0             0  Float64    ⋯
                                                     1 column and 2 rows omitted

#### Plotting Histograms for Treatment and Control groups in the variable inuidur1

In [10]:
treatment = filter(row -> row[:tg] in [2], df)
treatment = treatment[:,2:3]
control = filter(row -> row[:tg] in [0], df)
control = control[:,2:3]

3354×2 DataFrame
  Row │ tg       inuidur1 
      │ Float64  Float64  
──────┼───────────────────
    1 │     0.0      18.0
    2 │     0.0       1.0
    3 │     0.0      27.0
    4 │     0.0      27.0
    5 │     0.0      27.0
    6 │     0.0       9.0
    7 │     0.0      27.0
    8 │     0.0      15.0
    9 │     0.0      28.0
   10 │     0.0      12.0
   11 │     0.0      18.0
  ⋮   │    ⋮        ⋮
 3345 │     0.0      10.0
 3346 │     0.0      20.0
 3347 │     0.0      27.0
 3348 │     0.0      27.0
 3349 │     0.0      15.0
 3350 │     0.0       1.0
 3351 │     0.0      23.0
 3352 │     0.0       6.0
 3353 │     0.0       9.0
 3354 │     0.0      27.0
         3333 rows omitted

In [11]:
plotT = PlotlyJS.histogram(x=treatment[:,2], opacity=0.75)
PlotlyJS.plot(plotT)

data: [
  "histogram with fields opacity, type, and x"
]

layout: "layout with fields margin and template"

In [12]:
plotT = PlotlyJS.histogram(x=control[:,2], opacity=0.75)
PlotlyJS.plot(plotT)

data: [
  "histogram with fields opacity, type, and x"
]

layout: "layout with fields margin and template"

### Carry out covariate balance check

In [13]:
# couples variables combinations 
    combinations_upto(x, n) = Iterators.flatten(combinations(x, i) for i in 1:n)

# combinations without same couple
    expand_exp(args, deg::ConstantTerm) =
        tuple(((&)(terms...) for terms in combinations_upto(args, deg.n))...)

    StatsModels.apply_schema(t::FunctionTerm{typeof(^)}, sch::StatsModels.Schema, ctx::Type) =
        apply_schema.(expand_exp(t.args_parsed...), Ref(sch), ctx)

In [14]:
# linear regression

reg1 = @formula(T2 ~ (female+black+othrace+dep+q2+q3+q4+q5+q6+agelt35+agegt54+durable+lusd+husd)^2)
reg1 = apply_schema(reg1, schema(reg1, penn))

FormulaTerm
Response:
  T2(continuous)
Predictors:
  female(continuous)
  black(continuous)
  othrace(continuous)
  dep(DummyCoding:3→2)
  q2(continuous)
  q3(continuous)
  q4(continuous)
  q5(continuous)
  q6(continuous)
  agelt35(continuous)
  agegt54(continuous)
  durable(continuous)
  lusd(continuous)
  husd(continuous)
  female(continuous) & black(continuous)
  female(continuous) & othrace(continuous)
  female(continuous) & dep(DummyCoding:3→2)
  female(continuous) & q2(continuous)
  female(continuous) & q3(continuous)
  female(continuous) & q4(continuous)
  female(continuous) & q5(continuous)
  female(continuous) & q6(continuous)
  female(continuous) & agelt35(continuous)
  female(continuous) & agegt54(continuous)
  female(continuous) & durable(continuous)
  female(continuous) & lusd(continuous)
  female(continuous) & husd(continuous)
  black(continuous) & othrace(continuous)
  black(continuous) & dep(DummyCoding:3→2)
  black(continuous) & q2(continuous)
  black(continuous) & q3(

In [15]:
m1 = lm(reg1, penn)
table = regtable( "Covariate Balance Check" => m1) # coefficients, standard error, squared R, N (sample size )

                   | Covariate Balance Check 
                   |           (1)           
---------------------------------------------
       (Intercept) |                0.517*** 
                   |                 (0.158) 
            female |                   0.006 
                   |                 (0.130) 
             black |                  0.100* 
                   |                 (0.060) 
           othrace |                 -0.829* 
                   |                 (0.471) 
          dep: 1.0 |                   0.158 
                   |                 (0.186) 
          dep: 2.0 |                  -0.193 
                   |                 (0.163) 
                q2 |                  -0.109 
                   |                 (0.159) 
                q3 |                  -0.108 
                   |                 (0.159) 
                q4 |                  -0.062 
                   |                 (0.159) 
                q5 |              

### 3. Model specification

#### 3.1. No Adjustment Regression

In [16]:
# No adjustment (2-sample approach)

ols_cl = lm(@formula(log(inuidur1) ~ T2), penn)

table1 = regtable( "CL Model" => ols_cl)   

            | CL Model 
            |   (1)    
-----------------------
(Intercept) | 2.057*** 
            |  (0.021) 
         T2 | -0.079** 
            |  (0.032) 
-----------------------
          N |     5782 
      $R^2$ |    0.001 


#### 3.2. Classical Linear Regression

In [17]:
# adding controls
# Omitted dummies: q1, nondurable, muld

reg2 = @formula(log(inuidur1) ~ T2 + (female+black+othrace+dep+q2+q3+q4+q5+q6+agelt35+agegt54+durable+lusd+husd)^2)
reg2 = apply_schema(reg2, schema(reg2, penn))

ols_cra = lm(reg2, penn)
table2 = regtable("CRA model" => ols_cra)

                   | CRA model 
                   |    (1)    
-------------------------------
       (Intercept) |  2.447*** 
                   |   (0.381) 
                T2 |  -0.071** 
                   |   (0.032) 
            female | -0.943*** 
                   |   (0.314) 
             black | -0.508*** 
                   |   (0.146) 
           othrace |    -0.039 
                   |   (1.140) 
          dep: 1.0 |     0.280 
                   |   (0.451) 
          dep: 2.0 |     0.168 
                   |   (0.394) 
                q2 |     0.027 
                   |   (0.385) 
                q3 |    -0.354 
                   |   (0.384) 
                q4 |    -0.338 
                   |   (0.384) 
                q5 |    -0.178 
                   |   (0.383) 
                q6 |    -0.446 
                   |   (0.381) 
           agelt35 |    -0.326 
                   |   (0.326) 
           agegt54 |    -0.155 
                   |   (0.580) 
        

In [18]:
coefnames(reg2)

("log(inuidur1)", ["T2", "female", "black", "othrace", "dep: 1.0", "dep: 2.0", "q2", "q3", "q4", "q5"  …  "agelt35 & agegt54", "agelt35 & durable", "agelt35 & lusd", "agelt35 & husd", "agegt54 & durable", "agegt54 & lusd", "agegt54 & husd", "durable & lusd", "durable & husd", "lusd & husd"])

#### 3.3. Interactive Regression Adjustment

In [19]:
# demean function
function desv_mean(a)
    A = mean(a, dims = 1)
    M = zeros(Float64, size(X,1), size(X,2))
    
    for i in 1:size(a,2)
          M[:,i] = a[:,i] .- A[i]
    end
    return M
end    

# Matrix Model & demean
X = StatsModels.modelmatrix(reg1.rhs,penn)
X = desv_mean(X) # matrix format

5782×119 Matrix{Float64}:
 -0.400726  -0.118817  -0.00518852  -0.116569  …  -0.0549983  -0.0290557  0.0
 -0.400726  -0.118817  -0.00518852  -0.116569     -0.0549983  -0.0290557  0.0
 -0.400726  -0.118817  -0.00518852  -0.116569     -0.0549983  -0.0290557  0.0
 -0.400726  -0.118817  -0.00518852  -0.116569     -0.0549983  -0.0290557  0.0
  0.599274  -0.118817  -0.00518852  -0.116569     -0.0549983  -0.0290557  0.0
 -0.400726  -0.118817  -0.00518852   0.883431  …   0.945002   -0.0290557  0.0
  0.599274  -0.118817  -0.00518852  -0.116569     -0.0549983  -0.0290557  0.0
  0.599274  -0.118817  -0.00518852   0.883431     -0.0549983  -0.0290557  0.0
  0.599274  -0.118817  -0.00518852   0.883431     -0.0549983  -0.0290557  0.0
 -0.400726  -0.118817  -0.00518852  -0.116569     -0.0549983  -0.0290557  0.0
  0.599274  -0.118817  -0.00518852  -0.116569  …  -0.0549983  -0.0290557  0.0
  0.599274  -0.118817  -0.00518852  -0.116569     -0.0549983  -0.0290557  0.0
  0.599274  -0.118817  -0.00518852  -0

In [20]:
Y = select(penn, [:inuidur1,:T2]) # select inuidur1 y T2

X = DataFrame(hcat(X, Matrix(select(penn, [:T2])).*X), :auto)  # Joint X, (T2*X)

base = hcat(Y, X) # Joint inuidur1, T2, X y (T2*X)

base.inuidur1 = log.(base.inuidur1)  # log(inuidur1)

terms = term.(names(base)) # term.() let us to get all variables as objects

#interactive regression model

ols_ira  = lm(terms[1] ~ sum(terms[2:end]), base)

table3 = regtable("IRA Model" => ols_ira)

#terms[1] : select first variable. In this case, oucome of interest 
#sum(terms[2:end]) : independent variables as regresors in the linear regression

            | IRA Model 
            |    (1)    
------------------------
(Intercept) |  2.057*** 
            |   (0.021) 
         T2 |  -0.072** 
            |   (0.032) 
         x1 |    -0.666 
            |   (0.445) 
         x2 | -0.863*** 
            |   (0.270) 
         x3 |    -1.735 
            |   (2.173) 
         x4 |     0.036 
            |   (0.685) 
         x5 |     0.212 
            |   (0.497) 
         x6 |     0.000 
            |     (NaN) 
         x7 |  -0.367** 
            |   (0.150) 
         x8 |    -0.225 
            |   (0.154) 
         x9 |    -0.117 
            |   (0.149) 
        x10 |   -0.422* 
            |   (0.225) 
        x11 |    -0.678 
            |   (0.435) 
        x12 |    -0.304 
            |   (0.814) 
        x13 |    -0.838 
            |   (0.588) 
        x14 |    -0.099 
            |   (0.221) 
        x15 |     0.192 
            |   (0.477) 
        x16 |    -0.215 
            |   (0.139) 
        x17 |     0.599 


#### 3.4. Interactive Regression Adjustment using Lasso, with HDMJL

In [21]:
include("../Julia_Notebooks/hdmjl/hdmjl.jl")

In [22]:
X = StatsModels.modelmatrix(reg2.rhs,penn)
X = desv_mean(X)


D = DataFrame([X[:,1]], :auto)  # Treatment varaible

rename!(D, Dict(:x1 => :T2)) #rename x1 -> T2

X = DataFrame(hcat(X[:,2:end], X[:,1].*X[:,2:end]), :auto)  # Join Controls (X) + T4*X "interactive"

Y = select(penn, [:inuidur1]) #select just inuidur1

Y.inuidur1 = log.(Y.inuidur1)  # log(inuidur1)


5782-element Vector{Float64}:
 2.8903717578961645
 1.9459101490553132
 0.0
 3.295836866004329
 2.995732273553991
 3.295836866004329
 3.295836866004329
 2.1972245773362196
 3.295836866004329
 3.295836866004329
 2.70805020110221
 1.0986122886681098
 3.332204510175204
 ⋮
 2.302585092994046
 2.995732273553991
 3.295836866004329
 3.295836866004329
 2.70805020110221
 0.0
 3.1354942159291497
 1.791759469228055
 2.6390573296152584
 2.1972245773362196
 1.3862943611198906
 3.295836866004329

In [23]:
D_reg_0  = rlasso_arg( X, D, nothing, true, true, true, false, false, 
                    nothing, 1.1, nothing, 5000, 15, 10^(-5), -Inf, true, Inf, true )

rlasso_arg(5782×238 DataFrame
  Row │ x1         x2         x3           x4         x5         x6         x7 ⋯
      │ Float64    Float64    Float64      Float64    Float64    Float64    Fl ⋯
──────┼─────────────────────────────────────────────────────────────────────────
    1 │ -0.400726  -0.118817  -0.00518852  -0.116569   0.839329  -0.200104  -0 ⋯
    2 │ -0.400726  -0.118817  -0.00518852  -0.116569  -0.160671  -0.200104   0
    3 │ -0.400726  -0.118817  -0.00518852  -0.116569  -0.160671  -0.200104  -0
    4 │ -0.400726  -0.118817  -0.00518852  -0.116569  -0.160671  -0.200104  -0
    5 │  0.599274  -0.118817  -0.00518852  -0.116569  -0.160671  -0.200104  -0 ⋯
    6 │ -0.400726  -0.118817  -0.00518852   0.883431  -0.160671  -0.200104  -0
    7 │  0.599274  -0.118817  -0.00518852  -0.116569  -0.160671  -0.200104  -0
    8 │  0.599274  -0.118817  -0.00518852   0.883431  -0.160671  -0.200104  -0
    9 │  0.599274  -0.118817  -0.00518852   0.883431  -0.160671  -0.200104  -0 ⋯
   10 │ -0

In [24]:
D_resid = rlasso(D_reg_0)["residuals"]

5782-element Vector{Float64}:
 -0.41992390176409555
  0.5800760982359044
 -0.41992390176409555
 -0.41992390176409555
  0.5800760982359044
 -0.41992390176409555
 -0.41992390176409555
 -0.41992390176409555
 -0.41992390176409555
  0.5800760982359044
 -0.41992390176409555
  0.5800760982359044
 -0.41992390176409555
  ⋮
 -0.41992390176409555
 -0.41992390176409555
 -0.41992390176409555
 -0.41992390176409555
 -0.41992390176409555
 -0.41992390176409555
 -0.41992390176409555
 -0.41992390176409555
  0.5800760982359044
 -0.41992390176409555
  0.5800760982359044
 -0.41992390176409555

In [25]:
Y_reg_0  = rlasso_arg( X, Y, nothing, true, true, true, false, false, 
                    nothing, 1.1, nothing, 5000, 15, 10^(-5), -Inf, true, Inf, true )

rlasso_arg(5782×238 DataFrame
  Row │ x1         x2         x3           x4         x5         x6         x7 ⋯
      │ Float64    Float64    Float64      Float64    Float64    Float64    Fl ⋯
──────┼─────────────────────────────────────────────────────────────────────────
    1 │ -0.400726  -0.118817  -0.00518852  -0.116569   0.839329  -0.200104  -0 ⋯
    2 │ -0.400726  -0.118817  -0.00518852  -0.116569  -0.160671  -0.200104   0
    3 │ -0.400726  -0.118817  -0.00518852  -0.116569  -0.160671  -0.200104  -0
    4 │ -0.400726  -0.118817  -0.00518852  -0.116569  -0.160671  -0.200104  -0
    5 │  0.599274  -0.118817  -0.00518852  -0.116569  -0.160671  -0.200104  -0 ⋯
    6 │ -0.400726  -0.118817  -0.00518852   0.883431  -0.160671  -0.200104  -0
    7 │  0.599274  -0.118817  -0.00518852  -0.116569  -0.160671  -0.200104  -0
    8 │  0.599274  -0.118817  -0.00518852   0.883431  -0.160671  -0.200104  -0
    9 │  0.599274  -0.118817  -0.00518852   0.883431  -0.160671  -0.200104  -0 ⋯
   10 │ -0

In [26]:
Y_resid = rlasso(Y_reg_0)["residuals"]

5782-element Vector{Float64}:
  0.7317507898950092
 -0.05384734053849548
 -2.158620968001155
  1.137215898003174
  0.8371113055528355
  0.9765378557198169
  0.9765378557198169
 -0.12207443294829268
  1.137215898003174
  1.137215898003174
  0.5494292331010547
 -1.0600086793330457
  1.0129054998906915
  ⋮
  0.3028276034002372
  0.9959747839601821
  1.2960793764105205
  1.137215898003174
  0.886137646436092
 -1.9997574895938086
  1.321866894589781
 -0.36686149877310037
  0.8254300082758896
  0.19746708774241087
 -0.9330046491646217
  0.9765378557198169

In [27]:
D_resid = reshape(D_resid, length(D_resid), 1)

5782×1 Matrix{Float64}:
 -0.41992390176409555
  0.5800760982359044
 -0.41992390176409555
 -0.41992390176409555
  0.5800760982359044
 -0.41992390176409555
 -0.41992390176409555
 -0.41992390176409555
 -0.41992390176409555
  0.5800760982359044
 -0.41992390176409555
  0.5800760982359044
 -0.41992390176409555
  ⋮
 -0.41992390176409555
 -0.41992390176409555
 -0.41992390176409555
 -0.41992390176409555
 -0.41992390176409555
 -0.41992390176409555
 -0.41992390176409555
 -0.41992390176409555
  0.5800760982359044
 -0.41992390176409555
  0.5800760982359044
 -0.41992390176409555

In [28]:
Lasso_ira = lm(D_resid, Y_resid)

LinearModel{GLM.LmResp{Vector{Float64}}, GLM.DensePredChol{Float64, CholeskyPivoted{Float64, Matrix{Float64}}}}:

Coefficients:
──────────────────────────────────────────────────────────────────
         Coef.  Std. Error      t  Pr(>|t|)  Lower 95%   Upper 95%
──────────────────────────────────────────────────────────────────
x1  -0.0745733   0.0320861  -2.32    0.0202  -0.137474  -0.0116724
──────────────────────────────────────────────────────────────────


In [29]:
table = NamedArray(zeros(4, 5))

table[1,2] = GLM.coeftable(ols_cl).cols[1][2]
table[2,2] = GLM.coeftable(ols_cl).cols[2][2]
table[3,2] = GLM.coeftable(ols_cl).cols[5][2]
table[4,2] = GLM.coeftable(ols_cl).cols[6][2]
table[1,3] = GLM.coeftable(ols_cra).cols[1][2]
table[2,3] = GLM.coeftable(ols_cra).cols[2][2]
table[3,3] = GLM.coeftable(ols_cra).cols[5][2]
table[4,3] = GLM.coeftable(ols_cra).cols[6][2]
table[1,4] = GLM.coeftable(ols_ira).cols[1][2]
table[2,4] = GLM.coeftable(ols_ira).cols[2][2]
table[3,4] = GLM.coeftable(ols_ira).cols[5][2]
table[4,4] = GLM.coeftable(ols_ira).cols[6][2]
table[1,5] = GLM.coeftable(Lasso_ira).cols[1][1]
table[2,5] = GLM.coeftable(Lasso_ira).cols[2][1]
table[3,5] = GLM.coeftable(Lasso_ira).cols[5][1]
table[4,5] = GLM.coeftable(Lasso_ira).cols[6][1]

T = DataFrame(table, [ :"Outcome", :"CL", :"CRA", :"IRA", :"IRA W Lasso"])  # table to dataframe 
T[!,:Outcome] = string.(T[!,:Outcome])  # string - first column 

T[1,1] = "Estimation"
T[2,1] = "Standar error"
T[3,1] = "Lower bound CI"
T[4,1] = "Upper bound CI"

header = (["Outcome", "CL", "CRA", "IRA", "IRA W Lasso"])

pretty_table(T; backend = Val(:html), header = header, formatters=ft_round(4), alignment=:c)

<!DOCTYPE html>
 
 

 
 
 
 
 Outcome 
 CL 
 CRA 
 IRA 
 IRA W Lasso 
 
 
 
 
 Estimation 
 -0.0788 
 -0.0712 
 -0.0724 
 -0.0746 
 
 
 Standar error 
 0.0325 
 0.0321 
 0.0323 
 0.0321 
 
 
 Lower bound CI 
 -0.1425 
 -0.1341 
 -0.1356 
 -0.1375 
 
 
 Upper bound CI 
 -0.0152 
 -0.0083 
 -0.0092 
 -0.0117