# Modificación 1, script is correct!

# Python Basic Tutorial 

# Libraries

A library is a collection of modules or a single module. Modules are python programs that can be imported in another Python program. Libraries are the tools we will use to make our program.

In [1]:
import pandas as pd
import numpy as np

# Variables
Containers for store data values. This variable has a label or name. This variable is an object in memory.

### Python Types

There are three key python types: int, float, string and boolean.

In [2]:
a = 30
type(a)

int

In [6]:
a = 30.3
type(a)

float

In [7]:
a = "30"
type(a)

str

In [8]:
a = True
type(a)

bool

# List - THE KILLER
It is a ordered and mutable Python container.

In [12]:
a = [ 18, 20 , 30, "alex" ]
type(a)

list

### Indexing
Selecting elements starting from 0. I know it sounds crazy.

In [19]:
a[1:3]

[20, 30]

In [20]:
print(a[2])
print(a[0:2])

30
[18, 20]


# Dictionaries - THE WITCH
It is a unordered and mutable Python container.

In [21]:
# dictionary containing the population of the 5 largest german cities
population = {'Berlin': 3748148, 'Hamburg': 1822445, 'Munich': 1471508, 'Cologne': 1085664, 'Frankfurt': 753056 }

### Indexing
Selecting elements

In [22]:
population.keys()

dict_keys(['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt'])

In [24]:
population['Berlin']

3748148

In [26]:
population['Hamburg']

1822445

In [34]:
population_18_19 = {'Berlin': [3748148, 38000, "alex"], 'Hamburg': [1822445, 1922445], 
                    'Munich': 1471508, 'Cologne': 1085664, 'Frankfurt': 753056 , 'lima': 1100000}

In [35]:
population_18_19['lima']

1100000

In [41]:
Ciudades_alemanas = {'Berlin': [3748148, 38000, "alex"], 'Hamburg': [1822445, 1922445], 
                    'Munich': 1471508, 'Cologne': 1085664, 'Frankfurt': 753056}

Ciudades_lima = {'Lima': [3748148, 38000, "alex"], 'Huancayo': [1822445, 1922445]}

population = [Ciudades_alemanas,  Ciudades_lima]


[{'Berlin': [3748148, 38000, 'alex'],
  'Hamburg': [1822445, 1922445],
  'Munich': 1471508,
  'Cologne': 1085664,
  'Frankfurt': 753056},
 {'Lima': [3748148, 38000, 'alex'], 'Huancayo': [1822445, 1922445]}]

In [48]:
pop_germnay = Ciudades_alemanas["Berlin"][0] + Ciudades_alemanas["Hamburg"][0] 
pop_germnay

5570593

In [50]:
type(population)

list

# Numpy

They are arrays that are 50 times faster than lists. We can used them to make matrix operations.

In [51]:
a = np.array( [3, 4, 5])
print(a)
type(a)

[3 4 5]


numpy.ndarray

### [Key Methods](https://cs231n.github.io/python-numpy-tutorial/)

| Method | Description |
| -------- | ------------ |
|dtype  | type of elements in the array|
|ndim   |  dimension of array|
|shape  |  tuple with the dimmension of the array|
|size |  total number of elements in the array|

In [52]:
# 1-D array THIS IS NOT A VECTOR 
a = np.array([1,2,3,4,5])
print(a.size)
print(a.shape)
print(a.ndim)
print(a.dtype)

5
(5,)
1
int32


In [34]:
# 2-D array THIS IS A VECTOR
d = np.array([[1,2],[3,4]])
print( "d array", d.size)
print(d.shape)
print(d.ndim)
print(d.dtype)

5
(5,)
1
int32
d array 4
(2, 2)
2
int32


### ***[Array Creation Routines](https://numpy.org/doc/stable/reference/routines.array-creation.html)***


|Function|Return|
| --- | --- |
|arange( )|array of sequence|
|eye( )|diagonal array|
|ones( )|array of ones|
|zeros( )|array of zeros|

In [56]:
peru = np.arange(1, 10, 2)
peru

array([1, 3, 5, 7, 9])

In [57]:
peru = np.arange(start = 1,stop = 13,step = 5)
peru

array([ 1,  6, 11])

In [62]:
a4 = np.ones((10,10))
a4

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [64]:
a6 = np.zeros((3,20))
a6

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [66]:
lead = np.array([[1,2,3],[4,5,6]])
lead

array([[1, 2, 3],
       [4, 5, 6]])


### [Array Slicing](https://www.w3schools.com/python/numpy/numpy_array_slicing.asp)

In [67]:
# 1-D
z = np.array([1,8,9,10,15,12,3,16,20])
z

array([ 1,  8,  9, 10, 15, 12,  3, 16, 20])

In [69]:
print(z[1:6])

[ 8  9 10 15 12]


In [70]:
print(z[5])

12


### ***[Array Manipulation](https://numpy.org/doc/stable/reference/routines.array-manipulation.html)***

In [71]:
# 2-D

A_2D = np.array([[2,3,5,7],[11,13,17,19]])
A_2D

array([[ 2,  3,  5,  7],
       [11, 13, 17, 19]])

In [74]:
A_2D[:1,:3] 

array([[2, 3, 5]])

In [75]:
print( A_2D )
print( A_2D[:1,:3] )

[[ 2  3  5  7]
 [11 13 17 19]]
[[2 3 5]]


In [76]:
# RESHAPE
w = np.arange(0,25,1)
print( w )

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [77]:
print( w.reshape(5,5) )

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [79]:
# concatenate()
ej_1 = np.array ([[1,2],[3,4]])
ej_2 = np.array([[5,6]])
print("example 1" , ej_1)
print( "example 2" , ej_2)

example 1 [[1 2]
 [3 4]]
example 2 [[5 6]]


In [80]:
con = np.concatenate((ej_1, ej_2), axis = 0)
con

array([[1, 2],
       [3, 4],
       [5, 6]])

In [81]:
print( "example concatenate" , con )

example concatenate [[1 2]
 [3 4]
 [5 6]]


In [92]:
# add rows
mat_1 = np.arange(1,13,2).reshape((2,3))
print("mat1 \n" , mat_1)

mat_2 = np.zeros((4,3))
print("mat2 \n", mat_2)


mat1 
 [[ 1  3  5]
 [ 7  9 11]]
mat2 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [93]:
mat_3 = np.vstack((mat_1,mat_2))
print("mat3 \n", mat_3)

mat3 
 [[ 1.  3.  5.]
 [ 7.  9. 11.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [94]:
# Transpose
mat_5 = mat_1.T
print("mat5 \n" ,mat_5)

mat_6 = mat_2.T
print("mat6 \n" , mat_6)

# Add columns
mat_7 = np.hstack((mat_5,mat_6))
print("mat7 \n" , mat_7)

mat5 
 [[ 1  7]
 [ 3  9]
 [ 5 11]]
mat6 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
mat7 
 [[ 1.  7.  0.  0.  0.  0.]
 [ 3.  9.  0.  0.  0.  0.]
 [ 5. 11.  0.  0.  0.  0.]]


In [95]:
print("max \n", mat_5.max())
print("min \n", mat_5.min())
print("sum \n", mat_5.sum())

max 
 11
min 
 1
sum 
 36


# [Pandas](https://pandas.pydata.org/docs/user_guide/index.html)
It helps us to store data in a 2-dimensional labeled data structure with columns of potentially different types.

In [100]:
# crear dataframe
students = ["Alejandro","Pedro","Ramiro","Axel","Juan"]
math = [15,16,10,12,13]
english = [13,9,16,14,17]
art = [12,16,15,19,10]

# Make a dictionary
grades = {"Students": students, "Math":math, "English":english, "Art":art}
grades

{'Students': ['Alejandro', 'Pedro', 'Ramiro', 'Axel', 'Juan'],
 'Math': [15, 16, 10, 12, 13],
 'English': [13, 9, 16, 14, 17],
 'Art': [12, 16, 15, 19, 10]}

In [101]:
df1 = pd.DataFrame( grades )
df1

Students  Math  English  Art
0  Alejandro    15       13   12
1      Pedro    16        9   16
2     Ramiro    10       16   15
3       Axel    12       14   19
4       Juan    13       17   10

In [102]:
# Change columns names
df1.rename( columns = { "Students":'s', "Math":'m', "English":'e', "Art":'a'})

s   m   e   a
0  Alejandro  15  13  12
1      Pedro  16   9  16
2     Ramiro  10  16  15
3       Axel  12  14  19
4       Juan  13  17  10

In [103]:
# Add column and index row name
data = {'state': ['Lima', 'Piura', 'Tumbes', 'Cuzco', 'Ica', 'Puno'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [106]:
frame2 = pd.DataFrame(data, 
                      columns=["year", 'state', 'pop', 'debt'] ,
                      index=['one', 'two', 'three', 'four','five', 'six'] )
frame2
print( frame2 , "\n")

       year   state  pop debt
one    2000    Lima  1.5  NaN
two    2001   Piura  1.7  NaN
three  2002  Tumbes  3.6  NaN
four   2001   Cuzco  2.4  NaN
five   2002     Ica  2.9  NaN
six    2003    Puno  3.2  NaN 



In [108]:
# Ads column
frame2["debt"] = np.arange(1,12,2)
frame2

year   state  pop  debt
one    2000    Lima  1.5     1
two    2001   Piura  1.7     3
three  2002  Tumbes  3.6     5
four   2001   Cuzco  2.4     7
five   2002     Ica  2.9     9
six    2003    Puno  3.2    11

### [Slicing](https://www.opentechguides.com/how-to/article/pandas/193/index-slice-subset.html)

|Function|Return|
| --- | --- |
|iloc( )|Only numbers and booleans|
|loc( )|Name of columns and number of rows|

Everything starts form zero. Sorry :(

In [109]:
# Boolean complete list
frame2.iloc[[True, False, False, True, True, False], 1:3]

state  pop
one    Lima  1.5
four  Cuzco  2.4
five    Ica  2.9

In [110]:
# index number 
frame2.iloc[0:4, 1:3]

state  pop
one      Lima  1.5
two     Piura  1.7
three  Tumbes  3.6
four    Cuzco  2.4

In [94]:
frame2.loc[[0:4], ['state', 'pop']]
# problems
# row index in names

SyntaxError: invalid syntax (<ipython-input-94-4c600bd594ed>, line 1)

In [96]:
frame2.loc[['one', 'four'], ['state', 'pop']]

state  pop
one    Lima  1.5
four  Cuzco  2.4

In [99]:
frame2.sort_values(["year","pop"])

year   state  pop  debt
one    2000    Lima  1.5     1
two    2001   Piura  1.7     3
four   2001   Cuzco  2.4     7
five   2002     Ica  2.9     9
three  2002  Tumbes  3.6     5
six    2003    Puno  3.2    11

# If condition

Function **if** test conditions. 
- Equals: a == b
- Not Equals: a != b
- Less than: a < b
- Less than or equal to: a <= b
- Greater than: a > b
- Greater than or equal to: a >= b

<img src="https://www.dropbox.com/s/8xwqk2ze1116qvp/if-statement.jpg?dl=1" alt="image info" />

In [111]:
A = 20
B = 30

result = A == B
print( f'result A == B \t{result} \n')

result = A != B
print(f'result A != B \t  {result} \n' )

result = A > B
print(f'result A > B \t {result} \n')

result A == B 	False 

result A != B 	  True 

result A > B 	 False 



In [117]:
A = 30
B = 20
result = A > B
result

True

The structure of the code is the following: <br><br>

<font size="4">
if <font color='green'>test expresion</font>:<br>
&nbsp;&nbsp;&nbsp;&nbsp;Code to excute<br>
</font>

The function **if** tests the veracity of a logic expression. The result of test statement should be a **<font color='red'>boolean</font>**. In other words, the output of the test statemen must be **<font color='red'>True</font>** or **<font color='red'>False</font>**. To sum, any function that its output is **boolean** can be used as a test expression in the **if** function. 

### Tests more than 1 expression

We will use **elif**. This function allows us to add more test expressions.  <br><br>



<font size="4">
if <font color='green'>test expresion1</font>: <br>
&nbsp;&nbsp;&nbsp;&nbsp;Code1<br><br>
elif <font color='green'>test expresion2</font>:<br>
&nbsp;&nbsp;&nbsp;&nbsp;Code2<br><br>
elif <font color='green'>test expresion3</font>:<br>
&nbsp;&nbsp;&nbsp;&nbsp;Code3<br><br>
elif <font color='green'>test expresion4</font>:<br>
&nbsp;&nbsp;&nbsp;&nbsp;Code4<br><br>
elif <font color='green'>test expresion5</font>:<br>
&nbsp;&nbsp;&nbsp;&nbsp;Code5<br><br>
else :<br>
&nbsp;&nbsp;&nbsp;&nbsp;Code6<br><br>
</font>

Python will read the conditions of the test in order. 
If **Test expression 1** is `True`, the rest of the test expressions will not be evaluated. 
R execute **Code2** and will not test the next conditions. <br>

In case no Test expression is `True`, the **Code6** will be excuted.

In [118]:
A = 20
B = 30

if A == B:
    print( 'Test expresion 1 is True' )
    
elif A > B:
    print( 'Test expresion 2 is True' )

elif A >= B:
    print( 'Test expresion 3 is True' )
    
elif A < B:
    print( 'Test expresion 4 is True' )
    
elif A <= B:
    print( 'Test expresion 5 is True' )
    
else:
    print( 'Test expresion 6 is True' )

Test expresion 4 is True


# For Loops

A for loop is used for iterating over a sequence. It has the following structure:

<img src="https://www.dropbox.com/s/a51fbr4m0vpvobe/for_loop.jpg?dl=1" alt="image info" />



In [119]:
sequence = np.array( [15, 20, 25, 30 , 35 , 40 , 48 ] )
sequence

array([15, 20, 25, 30, 35, 40, 48])

In [126]:
i = 0
for element in sequence:
    i = i + 1 
    print( element  + i)

16
22
28
34
40
46
55


# Nested For Loop

In [127]:
age_class = [ [11, 12, 11] , [15, 16, 16] , [17, 17, 18]]
age_class

[[11, 12, 11], [15, 16, 16], [17, 17, 18]]

In [128]:
for classs in age_class:
    print( classs )
    
    for age in classs:
        print( age )

[11, 12, 11]
11
12
11
[15, 16, 16]
15
16
16
[17, 17, 18]
17
17
18


In [132]:
# secuencia
students = [ 'Miguel' , 'Anthony', 'Paul', 'Rodrigo', 'Jason' ]

# age
gr_age = [ 20, 18, 15, 20, 22]

# Loops
for student, age in zip( students , gr_age ):
    print(f'{ student } is { age }')

Miguel is 20
Anthony is 18
Paul is 15
Rodrigo is 20
Jason is 22


In [133]:
## Diferent dimmensions
# secuencia
students = [ 'Miguel' , 'Anthony', 'Paul', 'Rodrigo', 'Jason' ]

# Edades
gr_age = [ 20, 18, 15, 20 ]

for student, age in zip( students , gr_age ):
    print(f'{ student } is { age }')

Miguel is 20
Anthony is 18
Paul is 15
Rodrigo is 20


# Functions

- `Arguments` − Elements that the function will use to make operations. Arguments are optional and can have default values.

- `Function Body` − This defines what your function does.
- `return` − Specifies the variable that will be the output of the function.

Return Value − The return value of a function is the last expression in the function body to be evaluated.
<br><br>
<font size="4">
<font color='green'>def</font> function_name <font color='green'>(arg_1, arg_2, ...) </font>:<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;Function body <br>
    <br> &nbsp;&nbsp;&nbsp;&nbsp;<font color='green'>return</font> result<br>
</font>

In [ ]:
def function_name(x):
    
    # code
    
    return result


In [140]:
def suma(x, y):
    mate = (x + y)*15
    return mate

In [141]:
suma(5, 10)

225

In [ ]:
def da_positivos():
    # link de la data de positivos covid
    url = "https://cloud.minsa.gob.pe/s/Y8w3wHsEdYQSZRp/download"
    # guardando la data positivos covid
    csv_url = requests.get( url ).content
    
    # transformando de csv a dataframe
    data = pd.read_csv( io.StringIO( csv_url.decode( 'utf-8' ) ) , delimiter = ";")
    
    # Toma el año, mes y día
    data['year'] = data['FECHA_RESULTADO'].astype(str).str[:4]
    data['mes'] = data['FECHA_RESULTADO'].astype(str).str[4:6]
    data['day'] = data['FECHA_RESULTADO'].astype(str).str[6:8]
    
    # Eliminar data vacia en la variable FECHA_RESULTADO
    data = data[ data[ 'year' ] != 'nan']
    
    # Agrupa por departamento y año
    data1 = data.groupby(['DEPARTAMENTO', 'year'])[['UUID']].count().rename(columns = {'UUID':'Casos por year'} )
    
    return data1